def generate_pdf(result, confidence, img_path, gradcam_path):
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    import datetime

    file_path = "Brain_Tumor_Report.pdf"

    doc = SimpleDocTemplate(file_path, pagesize=letter)
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = styles["Title"]
    section_style = ParagraphStyle(
        name="Section",
        fontSize=14,
        spaceAfter=10,
        textColor=colors.blue
    )

    result_style = ParagraphStyle(
        name="Result",
        fontSize=16,
        textColor=colors.red if "Tumor" in result else colors.green,
        spaceAfter=10
    )

    content = []

    # Title
    content.append(Paragraph("🧠 Brain Tumor Detection Report", title_style))
    content.append(Spacer(1, 20))

    # Date
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content.append(Paragraph(f"<b>Generated on:</b> {now}", styles["Normal"]))
    content.append(Spacer(1, 20))

    # Result Section
    content.append(Paragraph("Diagnosis", section_style))
    content.append(Paragraph(f"<b>{result}</b>", result_style))
    content.append(Paragraph(f"Confidence: {confidence*100:.2f}%", styles["Normal"]))
    content.append(Spacer(1, 20))

    # Images Section
    content.append(Paragraph("MRI Scan", section_style))
    content.append(Image(img_path, width=4.5*inch, height=4.5*inch))
    content.append(Spacer(1, 15))

    content.append(Paragraph("Model Explanation (Grad-CAM)", section_style))
    content.append(Image(gradcam_path, width=4.5*inch, height=4.5*inch))
    content.append(Spacer(1, 20))

    # Disclaimer
    content.append(Paragraph(
        "⚠️ This report is generated by an AI model and is for educational purposes only. "
        "Consult a medical professional for diagnosis.",
        styles["Italic"]
    ))

    doc.build(content)

    return file_path